# Self-study try-it activity 3.1: Running simulations in Python

NumPy, short for "Numerical Python," is a library for working with arrays and mathematical operations in Python. It is the foundation of most scientific computing in Python and is crucial for data science, engineering and research applications.

NumPy is generally more efficient than Python lists; it runs faster and uses less memory because all elements share the same data type. It supports n-dimensional arrays, which are crucial for handling complex data structures and operations. 

NumPy also provides a broad range of mathematical functions, including tools for linear algebra, statistics and random number generation.

In [2]:
#importing the library for numpy
import numpy as np

This notebook covers the different operations of the NumPy array, including:

- Creating a NumPy array

- Picking up elements from the NumPy array

- Operations in an array

- Computing the frequency of occurrence of elements in an array

- Appending elements to an array

- Creating arrays within specific intervals

- Iterating array elements

- Encoding values in an array

- Reshaping the array in different dimensions

Since this module is about probability in machine learning, most of the examples of NumPy provided in this notebook are coin or dice examples.


## Creating a NumPy array

You can create a NumPy array using the `np.array()` function.

In [3]:
# Create a one-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])
print("One dimensional array is" , arr1)

# Create a two-dimensional array
arr2 = np.array([[1, 2], [3, 4]])
print("Two dimensional array is", arr2)

One dimensional array is [1 2 3 4 5]
Two dimensional array is [[1 2]
 [3 4]]


### Question 1

You throw a die several times and record the outcomes: "1 - 2 - 1 - 1 - 6 - 5 - 1". Now, record the values in an array.

In [4]:
#record the values in the array to `values`.

arr = np.array([1, 2, 1, 1, 6, 5, 1])
arr

array([1, 2, 1, 1, 6, 5, 1])

## Picking up elements from a NumPy array

Elements in a NumPy array can be accessed using indexing or slicing:

- Indexing allows direct access to individual elements using their index positions. 

- Slicing enables selection of a range of elements from the array.

In [5]:
#The first element of the array is printed by using index 0
print(arr1[0])
#The last element of the array is printed by using index -1
print(arr1[-1])

1
5


In [6]:
#The index elements can be mentioned for a 2D array for selecting array elements
print(arr2)

print(arr2[0,1])#prints the first row, second column of the array arr2

[[1 2]
 [3 4]]
2


In [8]:
l = [2, 3, 4, 5, 67]
l[::-1]


[67, 5, 4, 3, 2]

In [7]:
arr = np.array([10, 20, 30, 40, 50])

# Select elements from index 1 to index (4-1)
print(arr[1:4])
# Select every second element
print(arr[::2])
# Reverse the array
print(arr[::-1])

[20 30 40]
[10 30 50]
[50 40 30 20 10]


### Question 2

Now suppose you throw a die several times and record the outcomes: "1 - 2 - 1 - 1 - 6 - 5 - 1 - 3 -4 -6 -1". Answer the following questions based on the concepts of indexing and slicing.

In [9]:
#1. What is the number of elements in the array?
l = np.array([1, 2, 1, 1, 6, 5, 1, 3, 4, 6, 1])
len(l)

11

In [11]:
#2. Which is the second-to-last element in the array?
print(l[-2])

6


In [12]:
#3. Display the elements from index position 4 to the end of the array.
l[4:]

array([6, 5, 1, 3, 4, 6, 1])

In [13]:
#4. Display the elements from the 2nd position to the 7th position in the array.
l[2:8]


array([1, 1, 6, 5, 1, 3])

In [14]:
#5. Display the elements of the array in the reverse order.
l[::-1]

array([1, 6, 4, 3, 1, 5, 6, 1, 1, 2, 1])

## Operations in an array

These mathematical operations include addition, subtraction, multiplication and division of elements in arrays.

In [15]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Addition
result_add = np.add(array1, array2)
print("The addition of array1 and array1 is ", result_add)

# Subtraction
result_subtract = np.subtract(array1, array2)
print("The result of array1 subtracted from array 2 is ",result_subtract)

# Multiplication
result_multiply = np.multiply(array1, array2)
print("The result of product of array1 and array2 is ",result_multiply)
# Division
result_divide = np.divide(array1, array2)
print("The result of array1 divided by array2 is ", result_divide)


The addition of array1 and array1 is  [5 7 9]
The result of array1 subtracted from array 2 is  [-3 -3 -3]
The result of product of array1 and array2 is  [ 4 10 18]
The result of array1 divided by array2 is  [0.25 0.4  0.5 ]


In addition to the above operations, statistical operations like sum, mean, median, mode and standard deviation can also be performed on arrays.

In [16]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Calculate mean
mean = np.mean(arr)
print("The mean value of the array is" ,mean)

# Calculate median
median = np.median(arr)
print("The median value of the array is",median)

# Calculate standard deviation
std_dev = np.std(arr)
print("The standard deviation of the array is ",std_dev)

#Calculate sum
sum = np.sum(arr)
print("The sum of the array is ",sum)


The mean value of the array is 3.0
The median value of the array is 3.0
The standard deviation of the array is  1.4142135623730951
The sum of the array is  15


### Question 3

Imagine you throw two dice ten times and get the following readings:

- Dice 1 : 1 2 3 4 5 6 5 4 3 2

- Dice 2 : 1 1 2 2 4 5 6 3 2 1

Now, answer the following questions.

In [17]:
#1. Calculate the sum of each roll by adding corresponding elements from both arrays.
dice1 = np.array([1, 2, 3, 4, 5, 6, 5, 4, 3, 2])
dice2 = np.array([1, 1, 2, 2, 4, 5, 6, 3, 2, 1])
sum_of_rolls = np.add(dice1, dice2)
print("The sum of each roll is ",sum_of_rolls)

The sum of each roll is  [ 2  3  5  6  9 11 11  7  5  3]


In [18]:
#2. Calculate the average reading for each die over the 10 rolls.
average_dice1 = np.mean(dice1)
average_dice2 = np.mean(dice2)
print("The average reading for dice 1 is ",average_dice1)


The average reading for dice 1 is  3.5


In [ ]:
#3. Determine the median of the readings for each dice1 and dice2.
median_dice1 = np.median(dice1)
median_dice2 = np.median(dice2)
print("The median of the readings for dice 1 is ",median_dice1)
print("The median of the readings for dice 2 is ",median_dice2)



In [ ]:
#4. Multiply the readings of the two dice for each roll.
product_of_rolls = np.multiply(dice1, dice2)
print("The product of the readings for each roll is ",product_of_rolls)


In [20]:
#For a 2D array find out the mean for each row.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean_rows = np.mean(arr_2d, axis=1)
print(arr_2d)
print("The mean for each row is ",mean_rows)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
The mean for each row is  [2. 5. 8.]


## Computing the frequency of occurrence of elements in an array

The frequency of occurrence of elements can be computed using `np.unique` function.

In [21]:
values = np.array([1,2,1,1,6,5,1,3,4,6,1])
unique, counts = np.unique(values, return_counts=True)
dict(zip(unique, counts))

{np.int64(1): np.int64(5),
 np.int64(2): np.int64(1),
 np.int64(3): np.int64(1),
 np.int64(4): np.int64(1),
 np.int64(5): np.int64(1),
 np.int64(6): np.int64(2)}

In [ ]:
#For die 1, what is the frequency of occurrence of every element?




In [ ]:
#You suspect that die1 is not a fair die.
#Estimate the occurrence of each element and display the output in the form of a graph to prove your view




## Appending elements to an array

The `np.append()` function allows you to add elements to the end of an array. It does not modify the original array but returns a new array with the appended elements.

In [22]:
array3 = np.array([1,2,3])
array3 = np.append(array3, [2,4,3])
print("The appended array is ",array3)

The appended array is  [1 2 3 2 4 3]


In [ ]:
#You throw die1 three more times and get elements [2,3,3]. What is the list of numbers thrown by die1?
die1 = np.array([1, 2, 3, 4, 5, 6, 5, 4, 3, 2])
die1 = np.append(die1, [2, 3, 3])
print("The list of numbers thrown by die1 is ",die1)



## Creating arrays within specific intervals

Use the `np.arange()` function in NumPy to create arrays with evenly spaced values within a specified interval. It is similar to Python's `built-in range()` function. However, it works with both integers and floating-point numbers and returns a NumPy array.

The function is: `numpy.arange([start, ] stop, [step, ] dtype=None)`,

where:

- `start` is the starting value of the interval.

- `stop` is the end value of the interval.

- `step` is the spacing between values with a default of 1.

- `dtype` is the data type of the output array.

In [23]:
arr_arange = np.arange(5, 10)
print("The array created is given by",arr_arange)


The array created is given by [5 6 7 8 9]


In [24]:
#List all the two-digit positive integers from 10 to 100
two_digit_numbers = np.arange(10, 100)
print("The two-digit positive integers from 10 to 100 are ",two_digit_numbers)


The two-digit positive integers from 10 to 100 are  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [25]:
#How many numbers are there in the sequence S = 1,4,7,.....1005 for k?
sequence_S = np.arange(1, 1006, 3)
print("The sequence S is ",sequence_S)
print("The number of elements in the sequence S is ",len(sequence_S))


The sequence S is  [   1    4    7   10   13   16   19   22   25   28   31   34   37   40
   43   46   49   52   55   58   61   64   67   70   73   76   79   82
   85   88   91   94   97  100  103  106  109  112  115  118  121  124
  127  130  133  136  139  142  145  148  151  154  157  160  163  166
  169  172  175  178  181  184  187  190  193  196  199  202  205  208
  211  214  217  220  223  226  229  232  235  238  241  244  247  250
  253  256  259  262  265  268  271  274  277  280  283  286  289  292
  295  298  301  304  307  310  313  316  319  322  325  328  331  334
  337  340  343  346  349  352  355  358  361  364  367  370  373  376
  379  382  385  388  391  394  397  400  403  406  409  412  415  418
  421  424  427  430  433  436  439  442  445  448  451  454  457  460
  463  466  469  472  475  478  481  484  487  490  493  496  499  502
  505  508  511  514  517  520  523  526  529  532  535  538  541  544
  547  550  553  556  559  562  565  568  571  574  577  5

## Iterating array elements

You can iterate over elements in a NumPy array using basic Python loops or specialised NumPy functions like `nditer()` and `ndenumerate()`. Let's explore each method with examples.

In [26]:
arr1_iter = np.array([1, 2, 3, 4, 5])

for element in arr:
    print(element)


1
2
3
4
5


In [27]:

arr2_iter = np.array([[1, 2, 3], [4, 5, 6]])

for row in arr2_iter:
    for element in row:
        print(element)


1
2
3
4
5
6


In [28]:
arr3_iter = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

# Iterate over each element using nditer
for element in np.nditer(arr3_iter):
    print(element)


1
2
3
4
5
6
7
8
9


In [29]:
#If both index and values are required, enumerate is used
arr2_enumerate = np.array([[1, 2, 3], [4, 5, 6]])

for idx, element in np.ndenumerate(arr2_enumerate):
    print(f"Index: {idx}, Value: {element}")


Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6


In [30]:
#Suppose you have a 2D array representing the outcomes of rolling two dice multiple times.
#Each row represents a roll, and the columns represent the outcomes of the first and second die, respectively.
#Iterate over the array and print the index and value of each outcome.
#Calculate the total sum of all dice rolls.
dice_outcomes = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [2, 5],
    [6, 3]
])


## Encoding values in an array

To encode values in a NumPy array, you can use techniques like one-hot encoding or string encoding depending on the type of data and the purpose:

- One-hot encoding is commonly used in machine learning to convert categorical data into a binary matrix.

- To encode or decode strings, use string encoding.

In [31]:
genders = np.array(['Male', 'Female', 'Male', 'Female', 'Male'])

encoded_genders = np.where(genders == 'Male', 0, 1)
# Male is encoded to 0 and Female to 1
print("Original Genders:", genders)
print("Encoded Genders:", encoded_genders)


Original Genders: ['Male' 'Female' 'Male' 'Female' 'Male']
Encoded Genders: [0 1 0 1 0]


- You record a coin-throwing experiment 10 times and obtain 'H-T-H-H-H-T-T-T-T-H'

In [32]:
#A coin is thrown 10 times and the output is noted in an array.
#Encode this information to a numeric array of '0' and '1'
#Use may use 'H' is 1, and 'T' is 0.
coin_throw = np.array(['H','T', 'H','H','H','T','T','T','T','H'])


## Reshaping the array in different dimensions

To reshape an array using NumPy, you can use the `np.reshape()` function. This function allows you to change the shape of an array without altering its data.

In [33]:
arr_reshape = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2D array with 2 rows and 3 columns
new_arr = arr_reshape.reshape(2, 3)

print(new_arr)


[[1 2 3]
 [4 5 6]]


In [35]:
# A fair coin is tossed by two players and stored in an array.
#Each player played 3 times in a row.
#Show the  values played by each player
coin_toss = np.array(['H', 'T', 'H', 'T', 'H', 'T'])
coin_toss


array(['H', 'T', 'H', 'T', 'H', 'T'], dtype='<U1')